server:
  port: 9090
spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://192.168.1.17:8083
  profiles:
    default: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sriban97/green-config-server-props
          clone-on-start: true
          username:
          password:
          skip-ssl-validation: true
management:
  endpoints:
    web:
      exposure:
        include: "*"